package com.github.arci0066.worth.enumeration;

public enum OP_CODE {
    REGISTER,
    LOGIN,
    LOGOUT,
    LIST_USER,
    LIST_ONLINE_USER,
    LIST_PROJECTS,
    CREATE_PROJECT,
    ADD_MEMBER,
    SHOW_MEMBERS,
    SHOW_PROJECT_CARDS,
    SHOW_CARD,
    ADD_CARD,
    MOVE_CARD,
    GET_CARD_HISTORY,
    READ_CHAT,
    SEND_CHAT_MESSAGE,
    CANCEL_PROJECT
}
