public enum ANSWER_CODE {
    OP_OK,
    OP_FAIL,
    UNKNOWN_PROJECT,
    UNKNOWN_USER,
    UNKNOWN_CARD,
    WRONG_PASSWORD,
    EXISTING_USER,
    EXISTING_PROJECT,
    PERMISSION_DENIED,
    PROJECT_NOT_FINISHED,
    WRONG_LIST
}
